owner: mikoim
repo: uptime-paomoe
user-agent: KojBot
sites:
  - name: pao.moe
    url: https://pao.moe
assignees:
  - mikoim
status-website:
  cname: status.pao.moe
  logoUrl: https://cdn.pao.moe/status.svg
  name: "pao.moe Status"
  introTitle: ""
  introMessage: "2017年4月よりベストエフォート型のMastodonインスタンスを提供しておりま（´・ω・） ｽ"
  navbar:
    - title: pao.moe
      href: https://pao.moe/
