# Change these first
owner: mikoim # Your GitHub username
repo: uptime-paomoe # Your GitHub repository name

# Add your sites here
sites:
  - name: pao.moe
    url: https://pao.moe

assignees:
  - mikoim

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.pao.moe
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "pao.moe Status"
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: pao.moe
      href: https://pao.moe/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
